name: komga_reader
description: A minimalist Komga reading client (Android first; iOS, Windows and web later).
publish_to: "none"
version: 0.1.1+47

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  shaders:
    - shaders/denoise.frag
    - shaders/lanczos.frag
    - shaders/rcas.frag
    - shaders/colours.frag
    - shaders/easu.frag
    - shaders/curl.frag
  assets:
    - assets/icon.png
    - assets/docs/README.md
    - assets/docs/CHANGELOG.md
    - assets/docs/THIRD_PARTY_NOTICES.md
    - assets/licences/apache-2.0.txt
